version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: qualquer
      MYSQL_USER: xavlau
      MYSQL_PASSWORD: word

  word:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: xavlau
      WORDPRESS_DB_PASSWORD: word
      WORDPRESS_DB_NAME: qualquer


# version: '3'

# services:
#   wordpress: 
#     image: wordpress:latest
#     ports:
#       - 8000:80
#     environment:
#       WORDPRESS_DB_HOST: mysql:3306
#       WORDPRESS_DB_USER: wordpress
#       WORDPRESS_DB_PASSWORD: wordpress
#       WORDPRESS_DB_NAME: word
#     depends_on:
#       - mysql
#     restart: always
#   mysql:
#     image: mysql:5.7
#     environment:
#       MYSQL_ROOT_PASSWORD: somewordpress
#       MYSQL_DATABASE: wordpress
#       MYSQL_USER: wordpress
#       MYSQL_PASSWORD: wordpress
#     restart: always
#     volumes:
#       - db-data:/var/lib/mysql
# volumes:
#   db-data: {}